### ISSUE TITLE
Dashboard Ticket Anzeige vollständig defekt 

### ISSUE THREAD

**Issue by SiWa123571113** [FDHoho007/it-desk#5]
Wenn man auf ein belibiges Ticket geht, fehlen die Kommentare vollständig und im Administrationsfenster findet sich folgende Fehlermeldung:

<img width="941" alt="Screenshot 2022-09-16 at 17 53 37" src="https://user-images.githubusercontent.com/64312633/190680457-b81add44-c502-4b02-8ff8-bf8e103cbfe5.png">

**Comment by FDHoho007** [comment]
Vielen Dank für deine Meldung, dieser Tippfehler hat sich bei der Implementierung einer neuen Funktion eingeschlichen. Sollte behoben sein.

**Comment by SiWa123571113** [comment]
Leider kommt jetzt noch ein ähnlicher fehler an der gleichen stelle:
<img width="949" alt="Screenshot 2022-09-19 at 11 53 36" src="https://user-images.githubusercontent.com/64312633/190992989-a694ef1b-44fb-4f27-9dab-8adbfe6a9be8.png">
